/*
 * stmpe811_driver_hw.h
 *
 *  Created on: Feb 28, 2014
 *      Author: petera
 */

#ifndef STMPE811_DRIVER_HW_H_
#define STMPE811_DRIVER_HW_H_

enum {
  STMPE_REG_CHIP_ID       = 0x00,  // 16
  STMPE_REG_ID_VER        = 0x02,  // 8
  STMPE_REG_SYS_CTRL1     = 0x03,  // 8
  STMPE_REG_SYS_CTRL2     = 0x04,  // 8
  STMPE_REG_SPI_CFG       = 0x08,  // 8
  STMPE_REG_INT_CTRL      = 0x09,  // 8
  STMPE_REG_INT_EN        = 0x0a,  // 8
  STMPE_REG_INT_STA       = 0x0b,  // 8
  STMPE_REG_GPIO_INT_EN   = 0x0c,  // 8
  STMPE_REG_GPIO_INT_STA  = 0x0d,  // 8
  STMPE_REG_ADC_INT_EN    = 0x0e,  // 8
  STMPE_REG_ADC_INT_STA   = 0x0f,  // 8
  STMPE_REG_GPIO_SET_PIN  = 0x10,  // 8
  STMPE_REG_GPIO_CLR_PIN  = 0x11,  // 8
  STMPE_REG_GPIO_MP_STA   = 0x12,  // 8
  STMPE_REG_GPIO_DIR      = 0x13,  // 8
  STMPE_REG_GPIO_ED_STA   = 0x14,  // 8
  STMPE_REG_GPIO_RE       = 0x15,  // 8
  STMPE_REG_GPIO_FE       = 0x16,  // 8
  STMPE_REG_GPIO_AF       = 0x17,  // 8
  STMPE_REG_ADC_CTRL1     = 0x20,  // 8
  STMPE_REG_ADC_CTRL2     = 0x21,  // 8
  STMPE_REG_ADC_CAPT      = 0x22,  // 8
  STMPE_REG_ADC_DATA_CH0  = 0x30,  // 16
  STMPE_REG_ADC_DATA_CH1  = 0x32,  // 16
  STMPE_REG_ADC_DATA_CH2  = 0x34,  // 16
  STMPE_REG_ADC_DATA_CH3  = 0x36,  // 16
  STMPE_REG_ADC_DATA_CH4  = 0x38,  // 16
  STMPE_REG_ADC_DATA_CH5  = 0x3a,  // 16
  STMPE_REG_ADC_DATA_CH6  = 0x3c,  // 16
  STMPE_REG_ADC_DATA_CH7  = 0x3e,  // 16
  STMPE_REG_TSC_CTRL      = 0x40,  // 8
  STMPE_REG_TSC_CFG       = 0x41,  // 8
  STMPE_REG_WDW_TR_X      = 0x42,  // 16
  STMPE_REG_WDW_TR_Y      = 0x44,  // 16
  STMPE_REG_WDW_BL_X      = 0x46,  // 16
  STMPE_REG_WDW_BL_Y      = 0x48,  // 16
  STMPE_REG_FIFO_TH       = 0x4a,  // 8
  STMPE_REG_FIFO_STA      = 0x4b,  // 8
  STMPE_REG_FIFO_SIZE     = 0x4c,  // 16
  STMPE_REG_TSC_DATA_X    = 0x4d,  // 16
  STMPE_REG_TSC_DATA_Y    = 0x4f,  // 16
  STMPE_REG_TSC_DATA_Z    = 0x51,  // 16
  STMPE_REG_TSC_DATA_XYZ  = 0x52,  // 32
  STMPE_REG_TSC_FRACTION_Z = 0x56, // 8
  STMPE_REG_TSC_DATA      = 0x57,  // 8
  STMPE_REG_TSC_I_DRIVE   = 0x58,  // 8
  STMPE_REG_TSC_SHIELD    = 0x59,  // 8
  STMPE_REG_TEMP_CTRL     = 0x60,  // 8
  STMPE_REG_TEMP_DATA_H   = 0x61,  // 16 // todo checkup might be 61/8bit
  STMPE_REG_TEMP_DATA_L   = 0x62,  // 16 // todo checkup might be 61/8bit
  STMPE_REG_TEMP_TH       = 0x63,  // 16 // todo checkup might be 62/8bit
} stmpe811_reg;

#define STMPE_SYS_CTRL1_SOFT_RESET_MASK   (1<<1)
#define STMPE_SYS_CTRL1_HIBERNATE_MASK    (1<<0)
#define STMPE_SYS_CTRL1_SOFT_RESET_ON     STMPE_SYS_CTRL1_SOFT_RESET_MASK
#define STMPE_SYS_CTRL1_SOFT_RESET_OFF    0
#define STMPE_SYS_CTRL1_HIBERNATE_ON      STMPE_SYS_CTRL1_HIBERNATE_MASK
#define STMPE_SYS_CTRL1_HIBERNATE_OFF     0

#define STMPE_SYS_CTRL2_TS_MASK           (1<<3)
#define STMPE_SYS_CTRL2_GPIO_MASK         (1<<2)
#define STMPE_SYS_CTRL2_TSC_MASK          (1<<1)
#define STMPE_SYS_CTRL2_ADC_MASK          (1<<0)
#define STMPE_SYS_CTRL2_TS_OFF            STMPE_SYS_CTRL2_TS_MASK
#define STMPE_SYS_CTRL2_TS_ON             0
#define STMPE_SYS_CTRL2_GPIO_OFF          STMPE_SYS_CTRL2_GPIO_MASK
#define STMPE_SYS_CTRL2_GPIO_ON           0
#define STMPE_SYS_CTRL2_TSC_OFF           STMPE_SYS_CTRL2_TSC_MASK
#define STMPE_SYS_CTRL2_TSC_ON            0
#define STMPE_SYS_CTRL2_ADC_OFF           STMPE_SYS_CTRL2_ADC_MASK
#define STMPE_SYS_CTRL2_ADC_ON            0

#define STMPE_SPI_CFG_AUTO_INCR_MASK      (1<<2)
#define STMPE_SPI_CFG_SPI_CLK_MOD1_MASK   (1<<1)
#define STMPE_SPI_CFG_SPI_CLK_MOD0_MASK   (1<<0)
#define STMPE_SPI_CFG_AUTO_INCR_ON        STMPE_SPI_CFG_AUTO_INCR_MASK
#define STMPE_SPI_CFG_AUTO_INCR_OFF       0

#define STMPE_INT_CTRL_POLARITY_MASK      (1<<2)
#define STMPE_INT_CTRL_TYPE_MASK          (1<<1)
#define STMPE_INT_CTRL_GLOBAL_MASK        (1<<0)
#define STMPE_INT_CTRL_POLARITY_RISING    STMPE_INT_CTRL_POLARITY_MASK
#define STMPE_INT_CTRL_POLARITY_FALLING   0
#define STMPE_INT_CTRL_TYPE_EDGE          STMPE_INT_CTRL_TYPE_MASK
#define STMPE_INT_CTRL_TYPE_LEVEL         0
#define STMPE_INT_CTRL_GLOBAL_ENABLE      STMPE_INT_CTRL_GLOBAL_MASK
#define STMPE_INT_CTRL_GLOBAL_DISABLE     0

#define STMPE_ADC_CTRL1_SPL_TIME_MASK     0b01110000
#define STMPE_ADC_CTRL1_MOD_MASK          0b00001000
#define STMPE_ADC_CTRL1_MOD_REF_MASK      0b00000010
#define STMPE_ADC_CTRL1_SPL_TIME_36       0b00000000
#define STMPE_ADC_CTRL1_SPL_TIME_44       0b00010000
#define STMPE_ADC_CTRL1_SPL_TIME_56       0b00100000
#define STMPE_ADC_CTRL1_SPL_TIME_64       0b00110000
#define STMPE_ADC_CTRL1_SPL_TIME_80       0b01000000
#define STMPE_ADC_CTRL1_SPL_TIME_96       0b01010000
#define STMPE_ADC_CTRL1_SPL_TIME_124      0b01110000
#define STMPE_ADC_CTRL1_MOD_12B           0b00001000
#define STMPE_ADC_CTRL1_MOD_10B           0b00000000
#define STMPE_ADC_CTRL1_MOD_REF_EXTNL     0b00000010
#define STMPE_ADC_CTRL1_MOD_REF_INTNL     0b00000000

#define STMPE_ADC_CRTRL2_FREQ_MASK        0b00000011
#define STMPE_ADC_CRTRL2_FREQ_1_625       0b00000000
#define STMPE_ADC_CRTRL2_FREQ_3_25        0b00000001
#define STMPE_ADC_CRTRL2_FREQ_6_5         0b00000010

// todo TS

#define STMPE_TEMP_CTRL_THRES_RANGE_MASK  (1<<4)
#define STMPE_TEMP_CTRL_THRES_EN_MASK     (1<<3)
#define STMPE_TEMP_CTRL_ACQ_MOD_MASK      (1<<2)
#define STMPE_TEMP_CTRL_ACQ_MASK          (1<<1)
#define STMPE_TEMP_CTRL_ENABLE_MASK       (1<<0)
#define STMPE_TEMP_CTRL_THRES_RANGE_OVER  STMPE_TEMP_CTRL_THRES_RANGE_MASK
#define STMPE_TEMP_CTRL_THRES_RANGE_UNDER 0
#define STMPE_TEMP_CTRL_THRES_EN_ON       STMPE_TEMP_CTRL_THRES_EN_MASK
#define STMPE_TEMP_CTRL_THRES_EN_OFF      0
#define STMPE_TEMP_CTRL_ACQ_MOD_CONT      STMPE_TEMP_CTRL_ACQ_MOD_MASK
#define STMPE_TEMP_CTRL_ACQ_MOD_ONCE      0
#define STMPE_TEMP_CTRL_ACQ_ON            STMPE_TEMP_CTRL_ACQ_MASK
#define STMPE_TEMP_CTRL_ACQ_OFF           0
#define STMPE_TEMP_CTRL_ENABLE_ON         STMPE_TEMP_CTRL_ENABLE_MASK
#define STMPE_TEMP_CTRL_ENABLE_OFF        0


#endif /* STMPE811_DRIVER_HW_H_ */
